### PR TITLE
Fix issue where null discord user throws TypeError

### PR DESCRIPTION
**Pull request by mojiwa**
Fix for issue #365 
Early return badRequest if the user is either undefined or null.

### CODE REVIEW

**Comment by mojiwa** [comment]
Is this report something I need to worry about? I tried to look around for related tests, but didn't see any

**Comment by halkeye** [comment]
no its just saying code was added but no test was. It would be great if you could add tests, but we are in the middle of removing codecov

**Comment by niekcandaele** [comment]
> no its just saying code was added but no test was. It would be great if you could add tests, but we are in the middle of removing codecov

We've removed CodeClimate* Codecov will stay :). It would be great if you could add a test for this though?

**Comment by mojiwa** [comment]
> > no its just saying code was added but no test was. It would be great if you could add tests, but we are in the middle of removing codecov
> 
> We've removed CodeClimate* Codecov will stay :). It would be great if you could add a test for this though?

To be completely honest, I'm very new to web dev. I've amended existing tests before, but I wouldn't even know where to begin to create new test for this js file 🙈

**Comment by niekcandaele** [comment]
> > > no its just saying code was added but no test was. It would be great if you could add tests, but we are in the middle of removing codecov
> > 
> > 
> > We've removed CodeClimate* Codecov will stay :). It would be great if you could add a test for this though?
> 
> To be completely honest, I'm very new to web dev. I've amended existing tests before, but I wouldn't even know where to begin to create new test for this js file see_no_evil

That's fine, this controller will likely undergo significant refactoring once the Discord bot is abstracted anyways :) Thanks for your contribution!

**Pull request merged**
