### PR TITLE
Add error logging when giving via claim #412

### PR DESCRIPTION
**Pull request by cardinalion**

### CODE REVIEW

**Comment by cardinalion** [comment]
@halkeye I've no knowledge about codecov. Could you tell me why the test failed?

**Comment by halkeye** [comment]
It failed because the amount of code coverage that the tests cover went down.
In other words, a new line was added, but its not tested by tests, so the total % went down.

For a simple change likethis, its probably fine but up to @niekcandaele

**Review by niekcandaele — APPROVED** [review]

**Comment by niekcandaele** [comment]
Yeah no tests needed for this IMO

**Comment by cardinalion** [comment]
Thank you @halkeye for your explanation. Now this makes sense to me.

**Pull request merged**
