### PR TITLE
Make sure enrichData cannot throw inside the post-job logic

### PR DESCRIPTION
**Pull request by niekcandaele**

### CODE REVIEW

**Comment by halkeye** [comment]
log it on error?
test at all?

LGTM though

**Comment by halkeye** [comment]
is anything expecting player and it not being there going to break things?
does the calling function need to handle it?

**Comment by niekcandaele** [comment]
> is anything expecting player and it not being there going to break things?
> does the calling function need to handle it?

Nah, the enrich function tries to attach a player to logLine events. logLine events don't have a related player most of the time. Think logs like `Error: Object set to null reference`. 

The enrich function helps out a bit with custom hooks. Allows usage of the `player` variable in someone hooks into a log line containing a Steam ID for example

**Comment by niekcandaele** [comment]
This would have also been fixed if logging hook was refactored to use repeated jobs. This fix was a lot less work though,funny how things work out.

**Pull request merged**
