### PR TITLE
Remove a bunch of random leftover files

### PR DESCRIPTION
**Pull request by niekcandaele**

### CODE REVIEW

**Comment by halkeye** [comment]
nooo, editorconfig is important

**Comment by niekcandaele** [comment]
> nooo, editorconfig is important

Isn't it covered by the linter?

**Comment by halkeye** [comment]
and lefthook is what triggers eslint on commit, so important as well (though husky 5 is out)

**Comment by halkeye** [comment]
> Isn't it covered by the linter?

linter will handle js, but its still good practice, plus html, sh, json, and a bunch of other files

**Comment by niekcandaele** [comment]
> and lefthook is what triggers eslint on commit, so important as well (though husky 5 is out)

Husky does it, Lefthook was never configured correctly

**Comment by halkeye** [comment]
> Husky does it, Lefthook was never configured correctly

and yet, husky isn't in the deps

```
cat .git/hooks/pre-commit
#!/bin/sh

if [ "$LEFTHOOK" = "0" ]; then
  exit 0
fi

if [ -t 1 ] ; then
  exec < /dev/tty ; # <- enables interactive shell
fi


cmd="lefthook run pre-commit $@"

if lefthook -h >/dev/null 2>&1
then
  eval $cmd
elif bundle exec lefthook -h >/dev/null 2>&1
then
  bundle exec $cmd
elif npx lefthook -h >/dev/null 2>&1
then
  npx $cmd
elif yarn lefthook -h >/dev/null 2>&1
then
  yarn $cmd
else
  echo "Can't find lefthook in PATH"
fi
```

**Comment by niekcandaele** [comment]
Fixed now, you might need to do `npm rebuild` to get Husky to configure the hooks correctly

**Pull request merged**
