### PR TITLE
Improve docker-compose environment variables and removed worker port binding.

### PR DESCRIPTION
**Pull request by m4tm4t**
Also refactored a little the DBSTRING in .env.example to use vars instead of plain values

### CODE REVIEW

**Comment by niekcandaele** [comment]
Thanks! 

Looks good to me, I'd like @halkeye to give this a look as well before merging

For traceability, this fixes #237 and #236

**Comment by halkeye** [comment]
Does docker compose automatically read .env files? I know you can tell it to

**Comment by m4tm4t** [comment]
Oh you're right, there is a `env_file` option (used a old way to do that) and it's a lot more readable!

Now, about NODE_ENV, what do you think about defining it to .env file?

**Comment by niekcandaele** [comment]
Going to close this one in favour of https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/pull/328

Thanks for your PR though! The changes you made are also largely implemented in that PR

**Pull request closed without merging**
